play.http.secret.key="okCKogZSl+j9iHf2mG2vL22V4PrB4VV7OIJbcdflODA="
play.http.parser.maxMemoryBuffer: 1G

# JanusGraph configuration
db {
  provider: janusgraph
  janusgraph {
    storage {
      backend: berkeleyje
      directory: /opt/thp/thehive/db
    }
    index {
      search {
        directory: /opt/thp/thehive/index
      }
    }
  }
}